name: zoom-lib

on:
  push:
    paths:
      - "zoom_lib/**"
  pull_request:
    paths:
      - "zoom_lib/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          cd camera_lib
          pip install -r requirements.txt || echo "No requirements file."

      - name: Run Tests
        run: |
          cd zoom_lib
          pytest test_main.py

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        run: |
          cd camera_lib
          echo "Deploying zoom library..."
